<?php

namespace Database\Seeders;

use App\Models\Developer;
use App\Models\Game;
use App\Models\Genre;
use App\Models\Publisher;
use Illuminate\Database\Seeder;

class GameSeeder extends Seeder
{
    public function run(): void
    {
        $games = [
            [
                'title' => 'Death Stranding Director’s Cut',
                'slug' => 'death-stranding-directors-cut',
                'developer' => 'kojima-productions',
                'publisher' => '505-games',
                'steam_app_id' => 1850570,
                'genres' => ['action', 'adventure', 'story-rich'],
                'short' => 'Jelajahi Amerika yang terpecah sambil menghubungkan kembali komunitas-komunitas terpencil.',
                'description' => "Sam Porter Bridges membawa muatan melintasi bentang alam berbahaya dan menghadapi ancaman yang tidak biasa. Perencanaan rute, keseimbangan beban, dan interaksi tidak langsung dengan pemain lain membentuk pengalaman perjalanannya.\n\nEdisi Director’s Cut menambahkan aktivitas dan perangkat pendukung. Data harga pada DayatGames merupakan simulasi akademik.",
                'price' => 539999,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/1850570',
                'verified' => true,
                'release_date' => '2022-03-30',
                'cover' => 'death-stranding-directors-cut.webp',
                'featured' => true,
            ],
            [
                'title' => 'Forza Horizon 6',
                'slug' => 'forza-horizon-6',
                'developer' => 'playground-games',
                'publisher' => 'xbox-game-studios',
                'steam_app_id' => 2483190,
                'genres' => ['racing', 'open-world'],
                'short' => 'Pengalaman festival otomotif dunia terbuka dengan beragam kendaraan dan aktivitas balap.',
                'description' => "Forza Horizon berfokus pada kebebasan berkendara, koleksi mobil, serta event yang tersebar di dunia terbuka. Pemain dapat memilih balapan kompetitif maupun kegiatan santai.\n\nEntri ini mengikuti identitas yang terlihat pada aset pengguna. Detail rilis dan harga ditandai sebagai data demo sampai sumber resmi terverifikasi.",
                'price' => 899000,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/2483190',
                'verified' => true,
                'release_date' => '2026-05-18',
                'cover' => 'forza-horizon-6.webp',
                'featured' => true,
            ],
            [
                'title' => 'Atomic Heart',
                'slug' => 'atomic-heart',
                'developer' => 'mundfish',
                'publisher' => 'focus-entertainment',
                'steam_app_id' => 668580,
                'genres' => ['action', 'rpg', 'story-rich'],
                'short' => 'Hadapi fasilitas retro-futuristik yang kacau dengan kemampuan sarung tangan dan persenjataan improvisasi.',
                'description' => "Sebuah kompleks penelitian alternatif berubah menjadi medan pertempuran setelah sistem dan eksperimennya lepas kendali. Pertarungan memadukan senjata jarak dekat, senjata api, dan kemampuan khusus.\n\nEksplorasi lingkungan mengungkap latar dunia serta penyebab kekacauan. Harga yang digunakan merupakan data demonstrasi.",
                'price' => 549000,
                'discount' => 137250,
                'percent' => 75,
                'source' => 'https://store.steampowered.com/app/668580',
                'verified' => true,
                'release_date' => '2023-02-20',
                'cover' => 'atomic-heart.webp',
                'featured' => false,
            ],
            [
                'title' => 'God of War',
                'slug' => 'god-of-war',
                'developer' => 'santa-monica-studio',
                'publisher' => 'playstation-publishing',
                'steam_app_id' => 1593500,
                'genres' => ['action', 'adventure', 'story-rich'],
                'short' => 'Ikuti perjalanan Kratos dan Atreus melewati dunia mitologi Nordik yang keras.',
                'description' => "Kratos berusaha menjalani hidup baru sebagai ayah sambil membimbing Atreus dalam sebuah perjalanan pribadi. Pertarungan menekankan Leviathan Axe, posisi, dan pengelolaan kemampuan.\n\nEksplorasi, teka-teki, dan percakapan karakter menyatu dengan narasi keluarga. Harga DayatGames adalah simulasi akademik.",
                'price' => 729000,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/1593500',
                'verified' => true,
                'release_date' => '2022-01-14',
                'cover' => 'god-of-war.webp',
                'featured' => true,
            ],
            [
                'title' => 'Ghost of Tsushima Director’s Cut',
                'slug' => 'ghost-of-tsushima',
                'developer' => 'sucker-punch-productions',
                'publisher' => 'playstation-publishing',
                'steam_app_id' => 2215430,
                'genres' => ['action', 'adventure', 'open-world'],
                'short' => 'Bertahan di Tsushima sebagai Jin Sakai dengan gaya samurai maupun pendekatan Ghost.',
                'description' => "Pulau Tsushima menjadi ruang eksplorasi dengan duel, infiltrasi, dan cerita penduduk yang terdampak perang. Arah angin membantu navigasi tanpa memenuhi layar dengan penanda.\n\nPemain dapat mengembangkan teknik samurai dan alat Ghost sesuai situasi. Harga pada seed adalah data demo.",
                'price' => 879000,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/2215430',
                'verified' => true,
                'release_date' => '2024-05-16',
                'cover' => 'ghost-of-tsushima.webp',
                'featured' => true,
            ],
            [
                'title' => 'It Takes Two',
                'slug' => 'it-takes-two',
                'developer' => 'hazelight-studios',
                'publisher' => 'electronic-arts',
                'steam_app_id' => 1426210,
                'genres' => ['adventure', 'co-op', 'puzzle'],
                'short' => 'Petualangan kooperatif dua pemain dengan mekanik baru di setiap bagian cerita.',
                'description' => "Cody dan May berubah menjadi boneka dan harus bekerja sama melewati dunia yang terbentuk dari kehidupan keluarga mereka. Setiap pemain memiliki kemampuan yang saling melengkapi.\n\nTantangan platforming, puzzle, dan minigame dirancang untuk komunikasi dua pemain. Harga bersifat demonstrasi.",
                'price' => 479000,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/1426210',
                'verified' => true,
                'release_date' => '2021-03-25',
                'cover' => 'it-takes-two.webp',
                'featured' => false,
            ],
            [
                'title' => 'Grand Theft Auto V Enhanced',
                'slug' => 'grand-theft-auto-v',
                'developer' => 'rockstar-north',
                'publisher' => 'rockstar-games',
                'steam_app_id' => 3240220,
                'genres' => ['action', 'open-world'],
                'short' => 'Jelajahi Los Santos melalui kisah tiga protagonis dengan rangkaian misi kriminal.',
                'description' => "Michael, Franklin, dan Trevor memiliki latar serta kemampuan berbeda yang saling bertemu dalam serangkaian perampokan. Pemain dapat berganti karakter untuk melihat aksi dari sudut berbeda.\n\nDi luar misi utama tersedia aktivitas dunia terbuka yang beragam. Entri dan harga digunakan sebagai data demo lokal.",
                'price' => 439000,
                'discount' => 219500,
                'percent' => 50,
                'source' => 'https://store.steampowered.com/app/3240220',
                'verified' => true,
                'release_date' => '2025-03-04',
                'cover' => 'grand-theft-auto-v.webp',
                'featured' => false,
            ],
            [
                'title' => 'Kingdom Come: Deliverance II',
                'slug' => 'kingdom-come-deliverance-ii',
                'developer' => 'warhorse-studios',
                'publisher' => 'deep-silver',
                'steam_app_id' => 1771300,
                'genres' => ['rpg', 'open-world', 'story-rich'],
                'short' => 'Lanjutkan kisah Henry dalam RPG historis dengan pertarungan dan pilihan yang berdampak.',
                'description' => "Henry menjalani konflik baru di Bohemia abad pertengahan. Sistem dialog, reputasi, perlengkapan, dan pertarungan jarak dekat membentuk cara setiap masalah diselesaikan.\n\nDunia merespons tindakan pemain dan mendorong persiapan sebelum perjalanan. Harga DayatGames adalah simulasi.",
                'price' => 641000,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/1771300',
                'verified' => true,
                'release_date' => '2025-02-04',
                'cover' => 'kingdom-come-deliverance-ii.webp',
                'featured' => true,
            ],
            [
                'title' => 'Mafia: The Old Country',
                'slug' => 'mafia-the-old-country',
                'developer' => 'hangar-13',
                'publisher' => '2k',
                'steam_app_id' => 1941540,
                'genres' => ['action', 'adventure', 'story-rich'],
                'short' => 'Kisah kejahatan terarah yang membawa pemain ke akar dunia Mafia di Sisilia.',
                'description' => "Petualangan ini menempatkan karakter utama di tengah keluarga kriminal dan konflik pada latar Sisilia. Presentasi sinematik dan misi terarah menjadi fokus utama.\n\nAset berasal dari folder pengguna; harga pada katalog ini ditandai sebagai data demo akademik.",
                'price' => 570000,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/1941540',
                'verified' => true,
                'release_date' => '2025-08-07',
                'cover' => 'mafia-the-old-country.webp',
                'featured' => false,
            ],
            [
                'title' => 'Red Dead Redemption 2',
                'slug' => 'red-dead-redemption-2',
                'developer' => 'rockstar-studios',
                'publisher' => 'rockstar-games',
                'steam_app_id' => 1174180,
                'genres' => ['action', 'adventure', 'open-world'],
                'short' => 'Jalani kehidupan Arthur Morgan saat era kelompok penjahat di Amerika mulai berakhir.',
                'description' => "Arthur Morgan dan kelompok Van der Linde berpindah tempat sambil menghadapi tekanan hukum serta konflik internal. Dunia terbuka bereaksi terhadap kegiatan, reputasi, dan hubungan pemain.\n\nPerburuan, eksplorasi, kamp, dan misi naratif membangun ritme perjalanan. Harga merupakan data demo.",
                'price' => 879000,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/1174180',
                'verified' => true,
                'release_date' => '2019-12-05',
                'cover' => 'red-dead-redemption-2.webp',
                'featured' => true,
            ],
            [
                'title' => 'Road 96',
                'slug' => 'road-96',
                'developer' => 'digixart',
                'publisher' => 'thq-nordic',
                'steam_app_id' => 1466640,
                'genres' => ['adventure', 'story-rich'],
                'short' => 'Lakukan perjalanan prosedural menuju perbatasan dan temui karakter dengan kisah yang saling terhubung.',
                'description' => "Setiap perjalanan menghadirkan urutan pertemuan, pilihan, dan sumber daya yang berbeda. Keputusan pemain memengaruhi relasi serta keadaan dunia menjelang perubahan politik.\n\nStruktur perjalanan membuat cerita dapat dilihat dari banyak sudut. Harga di aplikasi adalah simulasi.",
                'price' => 214000,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/1466640',
                'verified' => true,
                'release_date' => '2021-08-16',
                'cover' => 'road-96.webp',
                'featured' => false,
            ],
            [
                'title' => 'Sons of the Forest',
                'slug' => 'sons-of-the-forest',
                'developer' => 'endnight-games',
                'publisher' => 'newnight',
                'steam_app_id' => 1326470,
                'genres' => ['horror', 'survival', 'open-world'],
                'short' => 'Bertahan di pulau terpencil dengan membangun perlindungan, mencari sumber daya, dan menghadapi ancaman.',
                'description' => "Pemain menjelajahi pulau yang menyimpan jaringan gua, fasilitas, dan makhluk berbahaya. Sistem crafting serta pembangunan memberi banyak pilihan untuk membuat basis.\n\nPerubahan musim memengaruhi persiapan dan ketersediaan sumber daya. Harga merupakan data demo.",
                'price' => 245999,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/1326470',
                'verified' => true,
                'release_date' => '2024-02-22',
                'cover' => 'sons-of-the-forest.webp',
                'featured' => false,
            ],
            [
                'title' => 'Detroit: Become Human',
                'slug' => 'detroit-become-human',
                'developer' => 'quantic-dream',
                'publisher' => 'quantic-dream',
                'steam_app_id' => 1222140,
                'genres' => ['adventure', 'story-rich'],
                'short' => 'Bentuk kisah tiga android melalui keputusan yang membuka dan menutup banyak cabang cerita.',
                'description' => "Connor, Kara, dan Markus menghadapi persoalan berbeda dalam masyarakat yang bergantung pada android. Pilihan dialog, investigasi, dan tindakan cepat dapat mengubah nasib karakter.\n\nDiagram cabang setelah adegan membantu melihat jalur yang belum dijelajahi. Harga adalah data demonstrasi.",
                'price' => 399000,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/1222140',
                'verified' => true,
                'release_date' => '2020-06-18',
                'cover' => 'detroit-become-human.webp',
                'featured' => false,
            ],
            [
                'title' => 'Ghost of Yōtei',
                'slug' => 'ghost-of-yotei',
                'developer' => 'sucker-punch-productions',
                'publisher' => 'playstation-publishing',
                'steam_app_id' => null,
                'genres' => ['action', 'adventure', 'open-world'],
                'short' => 'Petualangan aksi berlatar wilayah sekitar Gunung Yōtei dengan protagonis dan kisah baru.',
                'description' => "Aset menampilkan identitas Ghost of Yōtei dan digunakan sebagai contoh katalog DayatGames. Fokus entri berada pada perjalanan aksi dan eksplorasi dengan tema Jepang.\n\nPlatform, ketersediaan, dan harga pada seed belum diklaim sebagai data toko resmi; semuanya ditandai demo.",
                'price' => 879000,
                'discount' => null,
                'percent' => 0,
                'source' => null,
                'verified' => false,
                'release_date' => '2025-10-02',
                'cover' => 'ghost-of-yotei.webp',
                'featured' => true,
            ],
            [
                'title' => 'LEGO Batman: Legacy of the Dark Knight',
                'slug' => 'lego-batman-legacy-of-the-dark-knight',
                'developer' => 'tt-games',
                'publisher' => 'warner-bros-games',
                'steam_app_id' => 2215200,
                'genres' => ['action', 'adventure', 'co-op'],
                'short' => 'Petualangan LEGO Batman dengan aksi, humor, eksplorasi Gotham, dan permainan kooperatif.',
                'description' => "Aset pengguna menunjukkan judul Legacy of the Dark Knight. Entri ini dipakai untuk mendemonstrasikan katalog game mendatang tanpa mengklaim detail yang belum diverifikasi.\n\nTanggal, platform, dan harga resmi tidak ditetapkan; harga yang tampil merupakan nilai demo akademik.",
                'price' => 649000,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/2215200',
                'verified' => false,
                'release_date' => '2026-05-22',
                'cover' => 'lego-batman-legacy-of-the-dark-knight.webp',
                'featured' => false,
            ],
            [
                'title' => 'Hogwarts Legacy',
                'slug' => 'hogwarts-legacy',
                'developer' => 'avalanche-software',
                'publisher' => 'warner-bros-games',
                'steam_app_id' => 990080,
                'genres' => ['action', 'rpg', 'open-world'],
                'short' => 'Jelajahi Hogwarts dan wilayah sekitarnya sebagai murid dengan kemampuan sihir yang berkembang.',
                'description' => "Pemain mengikuti pelajaran, mempelajari mantra, meracik ramuan, dan menjelajahi area di luar sekolah. Pertarungan menggabungkan mantra ofensif, pertahanan, dan penggunaan lingkungan.\n\nPerlengkapan serta pilihan kemampuan mendukung gaya bermain berbeda. Harga pada DayatGames bersifat demo.",
                'price' => 799000,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/990080',
                'verified' => true,
                'release_date' => '2023-02-10',
                'cover' => 'hogwarts-legacy.webp',
                'featured' => false,
            ],
            [
                'title' => 'ELDEN RING',
                'slug' => 'elden-ring',
                'developer' => 'fromsoftware-inc',
                'publisher' => 'bandai-namco-entertainment',
                'steam_app_id' => 1245620,
                'genres' => ['action', 'rpg', 'open-world'],
                'short' => 'Bangkit sebagai Tarnished dan jelajahi Lands Between untuk menjadi Elden Lord.',
                'description' => "ELDEN RING adalah action RPG dunia terbuka yang memadukan eksplorasi bebas, dungeon kompleks, dan pertarungan menantang. Pemain dapat mengembangkan karakter melalui senjata, sihir, perlengkapan, dan beragam pendekatan bermain.\n\nData developer, publisher, tanggal rilis, dan harga diperiksa melalui halaman resmi Steam untuk wilayah Indonesia.",
                'price' => 599000,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/1245620',
                'verified' => true,
                'release_date' => '2022-02-24',
                'cover' => 'elden-ring.webp',
                'featured' => true,
            ],
            [
                'title' => 'Subnautica 2',
                'slug' => 'subnautica-2',
                'developer' => 'unknown-worlds-entertainment',
                'publisher' => 'unknown-worlds-entertainment',
                'steam_app_id' => 1962700,
                'genres' => ['adventure', 'survival', 'co-op'],
                'short' => 'Eksplorasi dunia laut asing, kumpulkan sumber daya, dan bangun alat untuk bertahan hidup.',
                'description' => "Aset pengguna dikenali sebagai Subnautica 2. Entri katalog berfokus pada tema eksplorasi bawah laut, ekosistem asing, crafting, dan kelangsungan hidup.\n\nRincian rilis dan harga resmi belum digunakan; nilai harga di aplikasi secara eksplisit merupakan data demo.",
                'price' => 350999,
                'discount' => null,
                'percent' => 0,
                'source' => 'https://store.steampowered.com/app/1962700',
                'verified' => true,
                'release_date' => '2026-05-14',
                'cover' => 'subnautica-2.webp',
                'featured' => false,
            ],
        ];

        foreach ($games as $data) {
            $developer = Developer::where('slug', $data['developer'])->firstOrFail();
            $publisher = Publisher::where('slug', $data['publisher'])->firstOrFail();

            $game = Game::updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'developer_id' => $developer->id,
                    'publisher_id' => $publisher->id,
                    'steam_app_id' => $data['steam_app_id'],
                    'title' => $data['title'],
                    'short_description' => $data['short'],
                    'description' => $data['description'],
                    'original_price' => $data['price'],
                    'discount_price' => $data['discount'],
                    'discount_percent' => $data['percent'],
                    'price_checked_at' => $data['verified'] ? '2026-07-24 15:00:00' : null,
                    'price_source_url' => $data['source'],
                    'price_is_demo' => ! $data['verified'],
                    'release_date' => $data['release_date'],
                    'platform' => 'PC',
                    'operating_system' => 'Windows',
                    'cover_image' => 'images/games/'.$data['cover'],
                    'hero_image' => 'images/games/'.$data['cover'],
                    'status' => 'published',
                    'is_featured' => $data['featured'],
                ],
            );

            $genreIds = Genre::whereIn('slug', $data['genres'])->pluck('id');
            $game->genres()->sync($genreIds);
        }
    }
}
